# Generated by Django 3.1.1 on 2020-10-06 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('image_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/media/causeImages')),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='media/media/flags')),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('shirt_type', models.CharField(max_length=30)),
                ('shirt_image', models.ImageField(upload_to='media/media/shirts')),
                ('original_image', models.ImageField(upload_to='media/media/shirts')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Atrocity', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.country')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('year_started', models.IntegerField()),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('website_url', models.URLField()),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.category')),
            ],
        ),
        migrations.AddField(
            model_name='atrocity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.category'),
        ),
        migrations.AddField(
            model_name='atrocity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.country'),
        ),
    ]
