# Generated by Django 3.0.8 on 2020-09-11 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atrocity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=30)),
                ('info', models.TextField()),
                ('image_url', models.TextField()),
                ('flagpic', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('shirt_type', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('shirt_image', models.ImageField(upload_to=None)),
                ('original_image', models.ImageField(upload_to=None)),
                ('Atrocity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.Atrocity')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.Category')),
            ],
        ),
        migrations.CreateModel(
            name='NonProfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.TextField()),
                ('description', models.TextField()),
                ('year_started', models.IntegerField()),
                ('mission_statement', models.TextField()),
                ('vision_statement', models.TextField()),
                ('website_url', models.URLField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.Category')),
            ],
        ),
        migrations.AddField(
            model_name='atrocity',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.Category'),
        ),
    ]
