# Generated by Django 3.0.8 on 2020-09-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='original_image',
            field=models.ImageField(upload_to='media/media/shirts'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='shirt_image',
            field=models.ImageField(upload_to='media/media/shirts'),
        ),
    ]
