# Generated by Django 3.0.8 on 2020-09-12 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0002_auto_20200912_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.ImageField(upload_to='media/media/flags')),
            ],
        ),
        migrations.RemoveField(
            model_name='atrocity',
            name='flagpic',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='description',
        ),
        migrations.AddField(
            model_name='atrocity',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.Country'),
        ),
        migrations.AlterField(
            model_name='shirt',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alt.Country'),
        ),
    ]
