# Generated by Django 3.1.1 on 2020-10-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0002_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Balance',
        ),
    ]
