# Generated by Django 3.1.1 on 2020-09-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0003_auto_20200912_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='atrocity',
            name='slug',
            field=models.SlugField(default=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='slug',
            field=models.SlugField(default='love'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shirt',
            name='slug',
            field=models.SlugField(default='love'),
            preserve_default=False,
        ),
    ]
