# Generated by Django 3.1.1 on 2020-09-24 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0004_auto_20200924_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atrocity',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='shirt',
            name='slug',
        ),
    ]
