# Generated by Django 3.1.1 on 2020-09-24 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0005_auto_20200924_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='Atrocity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Alt.atrocity'),
        ),
    ]
