# Generated by Django 3.1.1 on 2020-09-25 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0006_auto_20200924_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='slug',
            field=models.SlugField(default='love', unique=True),
            preserve_default=False,
        ),
    ]
