# Generated by Django 3.1.1 on 2020-09-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0007_nonprofit_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='shirt',
            name='slug',
            field=models.SlugField(default='Love', unique=True),
            preserve_default=False,
        ),
    ]
