# Generated by Django 3.1.1 on 2020-09-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alt', '0008_shirt_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirt',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
